package ec.com.antenasur.security.qr;

public enum ResultadoAccesoQr {
	VALIDO, TOKEN_INVALIDO, YA_UTILIZADO, REVOCADO, FUERA_DE_VIGENCIA, DOCUMENTO_NO_VIGENTE, PROCESO_NO_VIGENTE,
	MESA_NO_VIGENTE, PRESIDENTE_NO_VIGENTE, USUARIO_NO_AUTORIZADO, JRV_INCOMPLETA
}
