-- ============================================================================
-- TEC - Baseline inicial Flyway
-- ----------------------------------------------------------------------------
-- Uso previsto:
--   - Crear una base nueva desde cero.
--   - NO ejecutar sobre una base productiva existente.
--
-- Para una base existente usar:
--   baselineOnMigrate=true
--   baselineVersion=1
--
-- Los cambios posteriores deben iniciar en V2__descripcion.sql.
-- ============================================================================

DO $$
BEGIN
  IF EXISTS (
      SELECT 1
        FROM information_schema.tables
       WHERE table_schema IN ('public', 'tec')
         AND table_name IN (
             'tb_usuario', 'tb_rol', 'tb_persona', 'tb_iglesia',
             'padron', 'mesas', 'proceso_electoral', 'escrutinio'
         )
  ) THEN
    RAISE EXCEPTION 'V1__baseline_inicial.sql solo debe ejecutarse sobre una base nueva. Use baselineOnMigrate=true para bases existentes.';
  END IF;
END $$;

CREATE SCHEMA IF NOT EXISTS tec;

-- ============================================================================
-- Infraestructura base
-- ============================================================================

CREATE TABLE tec.tec_auditoria (
    aud_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_date TIMESTAMP,
    data_aud_status BOOLEAN,
    create_date TIMESTAMP,
    update_date TIMESTAMP,
    create_user VARCHAR(255),
    update_user VARCHAR(255)
);

CREATE TABLE public.tb_access_auditory (
    access_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    access_active BOOLEAN,
    access_browser VARCHAR(255),
    access_ip VARCHAR(255),
    access_login TIMESTAMP,
    access_logout TIMESTAMP,
    access_number_login INTEGER,
    access_session VARCHAR(255),
    access_status BOOLEAN,
    access_user VARCHAR(255),
    access_aplication VARCHAR(255)
);

CREATE TABLE public.tb_geograp (
    gelo_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gelo_codification_inec VARCHAR(255),
    gelo_name VARCHAR(255),
    gelo_observations VARCHAR(255),
    gelo_parent_id INTEGER,
    gelo_status BOOLEAN,
    pglo_id INTEGER,
    zone_id INTEGER,
    CONSTRAINT fk_geograp_parent
        FOREIGN KEY (gelo_parent_id) REFERENCES public.tb_geograp(gelo_id)
);

CREATE TABLE public.tb_persona (
    pers_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pers_nombre VARCHAR(255),
    pers_apellido VARCHAR(255),
    pers_documento VARCHAR(255),
    pers_tratamiento VARCHAR(255),
    pers_sexo VARCHAR(255),
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255)
);

CREATE TABLE public.tb_iglesia (
    igl_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    igl_nombre VARCHAR(255),
    igl_comunidad_barrio VARCHAR(255),
    igl_total_miembros INTEGER,
    igl_documento VARCHAR(255),
    gelo_id INTEGER,
    igl_version BIGINT NOT NULL DEFAULT 0,
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255),
    CONSTRAINT fk_iglesia_ubicacion
        FOREIGN KEY (gelo_id) REFERENCES public.tb_geograp(gelo_id),
    CONSTRAINT uk_iglesia_documento UNIQUE (igl_documento)
);

CREATE SEQUENCE IF NOT EXISTS public.seq_iglesia_codigo_generico START WITH 1 INCREMENT BY 1;

CREATE TABLE public.tb_iglesia_persona (
    igpe_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    igl_id INTEGER,
    pers_id INTEGER,
    igpe_f_desde TIMESTAMP,
    igpe_f_hasta TIMESTAMP,
    igpe_habilitado_padron BOOLEAN DEFAULT TRUE,
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255),
    CONSTRAINT fk_iglesia_persona_iglesia
        FOREIGN KEY (igl_id) REFERENCES public.tb_iglesia(igl_id),
    CONSTRAINT fk_iglesia_persona_persona
        FOREIGN KEY (pers_id) REFERENCES public.tb_persona(pers_id)
);

CREATE TABLE public.tb_rol (
    rol_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol_description VARCHAR(255),
    rol_nombre VARCHAR(255),
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255),
    CONSTRAINT uk_rol_nombre UNIQUE (rol_nombre)
);

CREATE TABLE public.tb_usuario (
    usu_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usu_f_expiracion TIMESTAMP,
    usu_link VARCHAR(255),
    usu_correo VARCHAR(255),
    usu_nombre VARCHAR(255),
    usu_clave VARCHAR(255),
    usu_clave_temp VARCHAR(255),
    usu_permanente BOOLEAN,
    pers_id INTEGER,
    igl_id INTEGER,
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255),
    CONSTRAINT fk_usuario_persona
        FOREIGN KEY (pers_id) REFERENCES public.tb_persona(pers_id),
    CONSTRAINT fk_usuario_iglesia
        FOREIGN KEY (igl_id) REFERENCES public.tb_iglesia(igl_id),
    CONSTRAINT uk_usuario_nombre UNIQUE (usu_nombre)
);

CREATE TABLE public.tb_menu (
    menu_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_accion VARCHAR(255),
    menu_nodo_final BOOLEAN,
    menu_ico VARCHAR(255),
    menu_img VARCHAR(255),
    menu_nombre VARCHAR(255),
    menu_orden INTEGER,
    menu_url VARCHAR(255),
    componente_id VARCHAR(255),
    menu_padre_id INTEGER,
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255),
    CONSTRAINT fk_menu_padre
        FOREIGN KEY (menu_padre_id) REFERENCES public.tb_menu(menu_id)
);

CREATE TABLE public.tb_menu_rol (
    mero_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id INTEGER,
    rol_id INTEGER,
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255),
    CONSTRAINT fk_menu_rol_menu
        FOREIGN KEY (menu_id) REFERENCES public.tb_menu(menu_id),
    CONSTRAINT fk_menu_rol_rol
        FOREIGN KEY (rol_id) REFERENCES public.tb_rol(rol_id),
    CONSTRAINT uk_menu_rol UNIQUE (menu_id, rol_id)
);

CREATE TABLE public.tb_role_user (
    rous_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol_id INTEGER,
    usu_id INTEGER,
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255),
    CONSTRAINT fk_rol_usuario_rol
        FOREIGN KEY (rol_id) REFERENCES public.tb_rol(rol_id),
    CONSTRAINT fk_rol_usuario_usuario
        FOREIGN KEY (usu_id) REFERENCES public.tb_usuario(usu_id),
    CONSTRAINT uk_rol_usuario UNIQUE (rol_id, usu_id)
);

-- ============================================================================
-- Nucleo TEC
-- ============================================================================

CREATE TABLE tec.catalogo_general (
    catalogo_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalogo_descripcion VARCHAR(255),
    catalogo_historial_id INTEGER,
    catalogo_nombre VARCHAR(255),
    catalogo_orden INTEGER,
    catalogo_info VARCHAR(255),
    catalogo_padre_id INTEGER,
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255),
    CONSTRAINT fk_catalogo_general_padre
        FOREIGN KEY (catalogo_padre_id) REFERENCES tec.catalogo_general(catalogo_id)
);

CREATE TABLE tec.cargos (
    cargo_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cargo_nombre VARCHAR(255),
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255)
);

CREATE TABLE tec.categoria_voto (
    cat_voto_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255),
    categoriavoto INTEGER,
    cat_orden INTEGER,
    lista_id INTEGER,
    proce_id INTEGER,
    cat_tipo VARCHAR(20) NOT NULL DEFAULT 'LEGACY',
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255)
);

CREATE TABLE tec.tipo_documentos (
    tipdoc_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipdoc_nombre VARCHAR(255),
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255)
);

CREATE TABLE tec.periodos (
    periodo_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo_nombre VARCHAR(255),
    periodo_descripcion VARCHAR(255),
    f_inicio TIMESTAMP,
    f_fin TIMESTAMP,
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255)
);

CREATE TABLE tec.proceso_electoral (
    proce_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proce_nombre VARCHAR(150) NOT NULL,
    proce_descripcion VARCHAR(500),
    proce_fecha_inicio TIMESTAMP,
    proce_fecha_fin TIMESTAMP,
    proce_activo BOOLEAN NOT NULL DEFAULT FALSE,
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255),
    CONSTRAINT uk_proceso_electoral_nombre UNIQUE (proce_nombre)
);

CREATE TABLE tec.cronograma_fase (
    cref_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proce_id INTEGER NOT NULL,
    cref_fase VARCHAR(40) NOT NULL,
    cref_titulo VARCHAR(150),
    cref_mensaje VARCHAR(1000),
    cref_severidad VARCHAR(20),
    cref_fecha_inicio TIMESTAMP NOT NULL,
    cref_fecha_fin TIMESTAMP NOT NULL,
    cref_permite_edicion BOOLEAN,
    cref_orden INTEGER,
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255),
    CONSTRAINT fk_cronograma_fase_proceso_electoral
        FOREIGN KEY (proce_id) REFERENCES tec.proceso_electoral(proce_id),
    CONSTRAINT uk_cronograma_fase_proceso_fase UNIQUE (proce_id, cref_fase)
);

CREATE TABLE tec.procesos (
    proceso_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actividad VARCHAR(255),
    ip VARCHAR(255),
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255)
);

CREATE TABLE tec.recintos (
    rec_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rec_nombre VARCHAR(255) NOT NULL,
    gelo_id INTEGER NOT NULL,
    estado_tarea VARCHAR(100),
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255),
    CONSTRAINT fk_recinto_ubicacion
        FOREIGN KEY (gelo_id) REFERENCES public.tb_geograp(gelo_id)
);

CREATE TABLE tec.mesas (
    mesa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mesa_nombre VARCHAR(255),
    rec_id INTEGER,
    gelo_id INTEGER,
    estado_tarea VARCHAR(100),
    totalvotos INTEGER,
    totalpapetelasuso INTEGER,
    totalausentismo INTEGER,
    tieneerrorconteo BOOLEAN,
    observacion VARCHAR(255),
    u_responsable VARCHAR(100),
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255),
    CONSTRAINT fk_mesa_recinto
        FOREIGN KEY (rec_id) REFERENCES tec.recintos(rec_id),
    CONSTRAINT fk_mesa_ubicacion
        FOREIGN KEY (gelo_id) REFERENCES public.tb_geograp(gelo_id)
);

CREATE TABLE tec.listas (
    lista_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lista_nombre VARCHAR(255),
    lista_slogan VARCHAR(255),
    lista_numero VARCHAR(255),
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255)
);

ALTER TABLE tec.categoria_voto
    ADD CONSTRAINT fk_categoria_voto_lista
        FOREIGN KEY (lista_id) REFERENCES tec.listas(lista_id),
    ADD CONSTRAINT fk_categoria_voto_proceso
        FOREIGN KEY (proce_id) REFERENCES tec.proceso_electoral(proce_id);

CREATE TABLE tec.correo_plantilla (
    corr_plan_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asunto VARCHAR(500),
    mensaje TEXT,
    descripcion VARCHAR(500),
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255)
);

CREATE TABLE tec.correos_enviados (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    de VARCHAR(255),
    para VARCHAR(255),
    usu_id INTEGER,
    detalles VARCHAR(255),
    corr_plan_id INTEGER,
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255),
    CONSTRAINT fk_correo_plantilla
        FOREIGN KEY (corr_plan_id) REFERENCES tec.correo_plantilla(corr_plan_id)
);

CREATE TABLE tec.documentos (
    doc_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_nombre VARCHAR(255),
    doc_path VARCHAR(255),
    tipdoc_id INTEGER,
    entidad_id INTEGER,
    doc_extension VARCHAR(255),
    doc_mime VARCHAR(255),
    doc_codigo VARCHAR(255),
    doc_hash_sha256 VARCHAR(64),
    doc_origen_id INTEGER,
    doc_contexto_hash VARCHAR(64),
    proce_id INTEGER,
    rec_id INTEGER,
    mesa_id INTEGER,
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255),
    CONSTRAINT fk_documentos_tipo_documento
        FOREIGN KEY (tipdoc_id) REFERENCES tec.tipo_documentos(tipdoc_id),
    CONSTRAINT fk_documentos_documento_origen
        FOREIGN KEY (doc_origen_id) REFERENCES tec.documentos(doc_id),
    CONSTRAINT fk_documentos_proceso_electoral
        FOREIGN KEY (proce_id) REFERENCES tec.proceso_electoral(proce_id),
    CONSTRAINT fk_documentos_recinto
        FOREIGN KEY (rec_id) REFERENCES tec.recintos(rec_id),
    CONSTRAINT fk_documentos_mesa
        FOREIGN KEY (mesa_id) REFERENCES tec.mesas(mesa_id)
);

CREATE TABLE tec.candidatos (
    cand_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    igpe_id INTEGER NOT NULL,
    lista_id INTEGER NOT NULL,
    periodo_id INTEGER,
    proce_id INTEGER NOT NULL,
    cargo_id INTEGER NOT NULL,
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255),
    CONSTRAINT fk_candidatos_iglesia_persona
        FOREIGN KEY (igpe_id) REFERENCES public.tb_iglesia_persona(igpe_id),
    CONSTRAINT fk_candidatos_lista
        FOREIGN KEY (lista_id) REFERENCES tec.listas(lista_id),
    CONSTRAINT fk_candidatos_periodo
        FOREIGN KEY (periodo_id) REFERENCES tec.periodos(periodo_id),
    CONSTRAINT fk_candidatos_proceso_electoral
        FOREIGN KEY (proce_id) REFERENCES tec.proceso_electoral(proce_id),
    CONSTRAINT fk_candidatos_cargo
        FOREIGN KEY (cargo_id) REFERENCES tec.catalogo_general(catalogo_id),
    CONSTRAINT uk_candidatos_proceso_lista_cargo_persona UNIQUE (proce_id, lista_id, cargo_id, igpe_id)
);

CREATE TABLE tec.tribunal (
    trib_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    igpe_id INTEGER NOT NULL,
    periodo_id INTEGER,
    proce_id INTEGER NOT NULL,
    cargo_id INTEGER NOT NULL,
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255),
    CONSTRAINT fk_tribunal_iglesia_persona
        FOREIGN KEY (igpe_id) REFERENCES public.tb_iglesia_persona(igpe_id),
    CONSTRAINT fk_tribunal_periodo
        FOREIGN KEY (periodo_id) REFERENCES tec.periodos(periodo_id),
    CONSTRAINT fk_tribunal_proceso_electoral
        FOREIGN KEY (proce_id) REFERENCES tec.proceso_electoral(proce_id),
    CONSTRAINT fk_tribunal_cargo
        FOREIGN KEY (cargo_id) REFERENCES tec.catalogo_general(catalogo_id),
    CONSTRAINT uk_tribunal_proceso_cargo UNIQUE (proce_id, cargo_id)
);

CREATE TABLE tec.padron (
    padron_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    igpe_id INTEGER NOT NULL,
    mesa_id INTEGER NOT NULL,
    periodo_id INTEGER,
    proce_id INTEGER NOT NULL,
    sufrago BOOLEAN NOT NULL DEFAULT FALSE,
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255),
    CONSTRAINT fk_padron_iglesia_persona
        FOREIGN KEY (igpe_id) REFERENCES public.tb_iglesia_persona(igpe_id),
    CONSTRAINT fk_padron_mesa
        FOREIGN KEY (mesa_id) REFERENCES tec.mesas(mesa_id),
    CONSTRAINT fk_padron_periodo
        FOREIGN KEY (periodo_id) REFERENCES tec.periodos(periodo_id),
    CONSTRAINT fk_padron_proceso_electoral
        FOREIGN KEY (proce_id) REFERENCES tec.proceso_electoral(proce_id),
    CONSTRAINT uk_padron_proceso_iglesia_persona UNIQUE (proce_id, igpe_id)
);

CREATE TABLE tec.miembros_jrv (
    miem_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    igpe_id INTEGER NOT NULL,
    mesa_id INTEGER NOT NULL,
    periodo_id INTEGER,
    proce_id INTEGER NOT NULL,
    cargo_id INTEGER NOT NULL,
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255),
    CONSTRAINT fk_miembros_jrv_iglesia_persona
        FOREIGN KEY (igpe_id) REFERENCES public.tb_iglesia_persona(igpe_id),
    CONSTRAINT fk_miembros_jrv_mesa
        FOREIGN KEY (mesa_id) REFERENCES tec.mesas(mesa_id),
    CONSTRAINT fk_miembros_jrv_periodo
        FOREIGN KEY (periodo_id) REFERENCES tec.periodos(periodo_id),
    CONSTRAINT fk_miembros_jrv_proceso_electoral
        FOREIGN KEY (proce_id) REFERENCES tec.proceso_electoral(proce_id),
    CONSTRAINT fk_miembros_jrv_cargo
        FOREIGN KEY (cargo_id) REFERENCES tec.catalogo_general(catalogo_id),
    CONSTRAINT uk_miembros_jrv_proceso_mesa_cargo UNIQUE (proce_id, mesa_id, cargo_id)
);

CREATE UNIQUE INDEX uk_miembros_jrv_activo_proceso_igpe
    ON tec.miembros_jrv(proce_id, igpe_id)
 WHERE COALESCE(estado, TRUE) = TRUE;

CREATE TABLE tec.escrutinio (
    escr_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mesa_id INTEGER NOT NULL,
    periodo_id INTEGER,
    proce_id INTEGER NOT NULL,
    cat_voto_id INTEGER NOT NULL,
    total_votos INTEGER NOT NULL DEFAULT 0,
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255),
    CONSTRAINT fk_escrutinio_mesa
        FOREIGN KEY (mesa_id) REFERENCES tec.mesas(mesa_id),
    CONSTRAINT fk_escrutinio_periodo
        FOREIGN KEY (periodo_id) REFERENCES tec.periodos(periodo_id),
    CONSTRAINT fk_escrutinio_proceso_electoral
        FOREIGN KEY (proce_id) REFERENCES tec.proceso_electoral(proce_id),
    CONSTRAINT fk_escrutinio_categoria_voto
        FOREIGN KEY (cat_voto_id) REFERENCES tec.categoria_voto(cat_voto_id),
    CONSTRAINT uk_escrutinio_proceso_mesa_categoria UNIQUE (proce_id, mesa_id, cat_voto_id)
);

CREATE TABLE tec.escrutinio_cabecera (
    esca_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mesa_id INTEGER NOT NULL,
    proce_id INTEGER NOT NULL,
    esca_estado VARCHAR(40) NOT NULL DEFAULT 'PENDIENTE',
    esca_presidente VARCHAR(100),
    esca_fecha_apertura TIMESTAMP,
    esca_fecha_inicio_conteo TIMESTAMP,
    esca_fecha_cierre TIMESTAMP,
    esca_total_sufragantes INTEGER NOT NULL DEFAULT 0,
    esca_total_votos_registrados INTEGER NOT NULL DEFAULT 0,
    esca_total_votos_validos INTEGER NOT NULL DEFAULT 0,
    esca_total_votos_blancos INTEGER NOT NULL DEFAULT 0,
    esca_total_votos_nulos INTEGER NOT NULL DEFAULT 0,
    esca_obs_apertura VARCHAR(1000),
    esca_obs_conteo VARCHAR(1000),
    esca_obs_cierre VARCHAR(1000),
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255),
    CONSTRAINT fk_escrutinio_cabecera_mesa
        FOREIGN KEY (mesa_id) REFERENCES tec.mesas(mesa_id),
    CONSTRAINT fk_escrutinio_cabecera_proceso
        FOREIGN KEY (proce_id) REFERENCES tec.proceso_electoral(proce_id),
    CONSTRAINT uk_escrutinio_cabecera_proceso_mesa UNIQUE (proce_id, mesa_id)
);

-- ============================================================================
-- Tablas de auditoria Hibernate Envers
-- ----------------------------------------------------------------------------
-- Se crean a partir de la estructura base para evitar divergencia de tipos.
-- Envers usa por defecto sufijo _AUD; PostgreSQL normaliza a minusculas.
-- ============================================================================

CREATE TABLE public.tb_geograp_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM public.tb_geograp t WITH NO DATA;
ALTER TABLE public.tb_geograp_aud ADD PRIMARY KEY (gelo_id, rev);
ALTER TABLE public.tb_geograp_aud ADD CONSTRAINT fk_tb_geograp_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE public.tb_persona_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM public.tb_persona t WITH NO DATA;
ALTER TABLE public.tb_persona_aud ADD PRIMARY KEY (pers_id, rev);
ALTER TABLE public.tb_persona_aud ADD CONSTRAINT fk_tb_persona_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE public.tb_iglesia_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM public.tb_iglesia t WITH NO DATA;
ALTER TABLE public.tb_iglesia_aud ADD PRIMARY KEY (igl_id, rev);
ALTER TABLE public.tb_iglesia_aud ADD CONSTRAINT fk_tb_iglesia_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE public.tb_iglesia_persona_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM public.tb_iglesia_persona t WITH NO DATA;
ALTER TABLE public.tb_iglesia_persona_aud ADD PRIMARY KEY (igpe_id, rev);
ALTER TABLE public.tb_iglesia_persona_aud ADD CONSTRAINT fk_tb_iglesia_persona_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE public.tb_rol_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM public.tb_rol t WITH NO DATA;
ALTER TABLE public.tb_rol_aud ADD PRIMARY KEY (rol_id, rev);
ALTER TABLE public.tb_rol_aud ADD CONSTRAINT fk_tb_rol_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE public.tb_usuario_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM public.tb_usuario t WITH NO DATA;
ALTER TABLE public.tb_usuario_aud ADD PRIMARY KEY (usu_id, rev);
ALTER TABLE public.tb_usuario_aud ADD CONSTRAINT fk_tb_usuario_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE public.tb_menu_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM public.tb_menu t WITH NO DATA;
ALTER TABLE public.tb_menu_aud ADD PRIMARY KEY (menu_id, rev);
ALTER TABLE public.tb_menu_aud ADD CONSTRAINT fk_tb_menu_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE public.tb_menu_rol_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM public.tb_menu_rol t WITH NO DATA;
ALTER TABLE public.tb_menu_rol_aud ADD PRIMARY KEY (mero_id, rev);
ALTER TABLE public.tb_menu_rol_aud ADD CONSTRAINT fk_tb_menu_rol_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE public.tb_role_user_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM public.tb_role_user t WITH NO DATA;
ALTER TABLE public.tb_role_user_aud ADD PRIMARY KEY (rous_id, rev);
ALTER TABLE public.tb_role_user_aud ADD CONSTRAINT fk_tb_role_user_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE tec.catalogo_general_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM tec.catalogo_general t WITH NO DATA;
ALTER TABLE tec.catalogo_general_aud ADD PRIMARY KEY (catalogo_id, rev);
ALTER TABLE tec.catalogo_general_aud ADD CONSTRAINT fk_catalogo_general_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE tec.cargos_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM tec.cargos t WITH NO DATA;
ALTER TABLE tec.cargos_aud ADD PRIMARY KEY (cargo_id, rev);
ALTER TABLE tec.cargos_aud ADD CONSTRAINT fk_cargos_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE tec.categoria_voto_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM tec.categoria_voto t WITH NO DATA;
ALTER TABLE tec.categoria_voto_aud ADD PRIMARY KEY (cat_voto_id, rev);
ALTER TABLE tec.categoria_voto_aud ADD CONSTRAINT fk_categoria_voto_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE tec.tipo_documentos_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM tec.tipo_documentos t WITH NO DATA;
ALTER TABLE tec.tipo_documentos_aud ADD PRIMARY KEY (tipdoc_id, rev);
ALTER TABLE tec.tipo_documentos_aud ADD CONSTRAINT fk_tipo_documentos_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE tec.periodos_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM tec.periodos t WITH NO DATA;
ALTER TABLE tec.periodos_aud ADD PRIMARY KEY (periodo_id, rev);
ALTER TABLE tec.periodos_aud ADD CONSTRAINT fk_periodos_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE tec.proceso_electoral_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM tec.proceso_electoral t WITH NO DATA;
ALTER TABLE tec.proceso_electoral_aud ADD PRIMARY KEY (proce_id, rev);
ALTER TABLE tec.proceso_electoral_aud ADD CONSTRAINT fk_proceso_electoral_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE tec.cronograma_fase_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM tec.cronograma_fase t WITH NO DATA;
ALTER TABLE tec.cronograma_fase_aud ADD PRIMARY KEY (cref_id, rev);
ALTER TABLE tec.cronograma_fase_aud ADD CONSTRAINT fk_cronograma_fase_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE tec.recintos_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM tec.recintos t WITH NO DATA;
ALTER TABLE tec.recintos_aud ADD PRIMARY KEY (rec_id, rev);
ALTER TABLE tec.recintos_aud ADD CONSTRAINT fk_recintos_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE tec.mesas_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM tec.mesas t WITH NO DATA;
ALTER TABLE tec.mesas_aud ADD PRIMARY KEY (mesa_id, rev);
ALTER TABLE tec.mesas_aud ADD CONSTRAINT fk_mesas_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE tec.listas_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM tec.listas t WITH NO DATA;
ALTER TABLE tec.listas_aud ADD PRIMARY KEY (lista_id, rev);
ALTER TABLE tec.listas_aud ADD CONSTRAINT fk_listas_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE tec.correo_plantilla_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM tec.correo_plantilla t WITH NO DATA;
ALTER TABLE tec.correo_plantilla_aud ADD PRIMARY KEY (corr_plan_id, rev);
ALTER TABLE tec.correo_plantilla_aud ADD CONSTRAINT fk_correo_plantilla_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE tec.correos_enviados_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM tec.correos_enviados t WITH NO DATA;
ALTER TABLE tec.correos_enviados_aud ADD PRIMARY KEY (id, rev);
ALTER TABLE tec.correos_enviados_aud ADD CONSTRAINT fk_correos_enviados_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE tec.documentos_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM tec.documentos t WITH NO DATA;
ALTER TABLE tec.documentos_aud ADD PRIMARY KEY (doc_id, rev);
ALTER TABLE tec.documentos_aud ADD CONSTRAINT fk_documentos_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE tec.candidatos_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM tec.candidatos t WITH NO DATA;
ALTER TABLE tec.candidatos_aud ADD PRIMARY KEY (cand_id, rev);
ALTER TABLE tec.candidatos_aud ADD CONSTRAINT fk_candidatos_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE tec.tribunal_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM tec.tribunal t WITH NO DATA;
ALTER TABLE tec.tribunal_aud ADD PRIMARY KEY (trib_id, rev);
ALTER TABLE tec.tribunal_aud ADD CONSTRAINT fk_tribunal_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE tec.padron_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM tec.padron t WITH NO DATA;
ALTER TABLE tec.padron_aud ADD PRIMARY KEY (padron_id, rev);
ALTER TABLE tec.padron_aud ADD CONSTRAINT fk_padron_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE tec.miembros_jrv_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM tec.miembros_jrv t WITH NO DATA;
ALTER TABLE tec.miembros_jrv_aud ADD PRIMARY KEY (miem_id, rev);
ALTER TABLE tec.miembros_jrv_aud ADD CONSTRAINT fk_miembros_jrv_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE tec.escrutinio_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM tec.escrutinio t WITH NO DATA;
ALTER TABLE tec.escrutinio_aud ADD PRIMARY KEY (escr_id, rev);
ALTER TABLE tec.escrutinio_aud ADD CONSTRAINT fk_escrutinio_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

CREATE TABLE tec.escrutinio_cabecera_aud AS SELECT t.*, 0::INTEGER AS rev, 0::SMALLINT AS revtype FROM tec.escrutinio_cabecera t WITH NO DATA;
ALTER TABLE tec.escrutinio_cabecera_aud ADD PRIMARY KEY (esca_id, rev);
ALTER TABLE tec.escrutinio_cabecera_aud ADD CONSTRAINT fk_escrutinio_cabecera_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id);

-- ============================================================================
-- Indices
-- ============================================================================

CREATE INDEX idx_iglesia_gelo_id ON public.tb_iglesia(gelo_id);
CREATE INDEX idx_iglesia_persona_igl_id ON public.tb_iglesia_persona(igl_id);
CREATE INDEX idx_iglesia_persona_pers_id ON public.tb_iglesia_persona(pers_id);
CREATE INDEX idx_menu_padre_id ON public.tb_menu(menu_padre_id);
CREATE INDEX idx_usuario_persona_id ON public.tb_usuario(pers_id);
CREATE INDEX idx_usuario_iglesia_id ON public.tb_usuario(igl_id);
CREATE INDEX idx_documentos_entidad_tipo_estado ON tec.documentos(entidad_id, tipdoc_id, estado);
CREATE INDEX idx_documentos_origen ON tec.documentos(doc_origen_id);
CREATE UNIQUE INDEX ux_documentos_acta_contexto_activa
    ON tec.documentos(entidad_id, tipdoc_id, doc_contexto_hash)
    WHERE estado = TRUE AND doc_contexto_hash IS NOT NULL;
CREATE UNIQUE INDEX ux_documentos_acta_firmada_origen_activa
    ON tec.documentos(doc_origen_id)
    WHERE estado = TRUE AND doc_origen_id IS NOT NULL;
CREATE INDEX idx_documentos_mesa_proceso_estado ON tec.documentos(mesa_id, proce_id, estado);
CREATE INDEX idx_documentos_recinto_proceso_estado ON tec.documentos(rec_id, proce_id, estado);

CREATE INDEX idx_proceso_electoral_activo ON tec.proceso_electoral(proce_activo);
CREATE INDEX idx_proceso_electoral_fechas ON tec.proceso_electoral(proce_fecha_inicio, proce_fecha_fin);
CREATE INDEX idx_cronograma_fase_proce_id ON tec.cronograma_fase(proce_id);
CREATE INDEX idx_cronograma_fase_fechas ON tec.cronograma_fase(cref_fecha_inicio, cref_fecha_fin);
CREATE INDEX idx_recintos_gelo_id ON tec.recintos(gelo_id);
CREATE INDEX idx_categoria_voto_proceso_tipo_estado ON tec.categoria_voto(proce_id, cat_tipo, estado);
CREATE INDEX idx_categoria_voto_lista_proceso ON tec.categoria_voto(lista_id, proce_id);
CREATE UNIQUE INDEX ux_categoria_voto_lista_proceso_activa
    ON tec.categoria_voto(lista_id, proce_id)
    WHERE estado = TRUE
      AND cat_tipo = 'LISTA'
      AND lista_id IS NOT NULL
      AND proce_id IS NOT NULL;
CREATE INDEX idx_padron_proce_id ON tec.padron(proce_id);
CREATE INDEX idx_padron_mesa_id ON tec.padron(mesa_id);
CREATE INDEX idx_padron_igpe_id ON tec.padron(igpe_id);
CREATE INDEX idx_padron_proceso_mesa ON tec.padron(proce_id, mesa_id);
CREATE INDEX idx_candidatos_proce_id ON tec.candidatos(proce_id);
CREATE INDEX idx_candidatos_lista_id ON tec.candidatos(lista_id);
CREATE INDEX idx_candidatos_cargo_id ON tec.candidatos(cargo_id);
CREATE INDEX idx_candidatos_igpe_id ON tec.candidatos(igpe_id);
CREATE INDEX idx_escrutinio_proce_id ON tec.escrutinio(proce_id);
CREATE INDEX idx_escrutinio_mesa_id ON tec.escrutinio(mesa_id);
CREATE INDEX idx_escrutinio_categoria_id ON tec.escrutinio(cat_voto_id);
CREATE INDEX idx_escrutinio_cabecera_proce_id ON tec.escrutinio_cabecera(proce_id);
CREATE INDEX idx_escrutinio_cabecera_mesa_id ON tec.escrutinio_cabecera(mesa_id);
CREATE INDEX idx_escrutinio_cabecera_estado ON tec.escrutinio_cabecera(esca_estado);
CREATE INDEX idx_miembros_jrv_proce_id ON tec.miembros_jrv(proce_id);
CREATE INDEX idx_miembros_jrv_mesa_id ON tec.miembros_jrv(mesa_id);
CREATE INDEX idx_miembros_jrv_igpe_id ON tec.miembros_jrv(igpe_id);
CREATE INDEX idx_miembros_jrv_proceso_igpe ON tec.miembros_jrv(proce_id, igpe_id);
CREATE INDEX idx_tribunal_proce_id ON tec.tribunal(proce_id);
CREATE INDEX idx_tribunal_cargo_id ON tec.tribunal(cargo_id);
CREATE INDEX idx_tribunal_igpe_id ON tec.tribunal(igpe_id);

-- ============================================================================
-- Vistas de consulta
-- ============================================================================

CREATE OR REPLACE VIEW tec.vw_lugar_votacion AS
SELECT p.padron_id,
       i.igl_nombre AS iglesia,
       i.igl_comunidad_barrio AS comunicad,
       pe.pers_documento AS cedula,
       CONCAT_WS(' ', pe.pers_nombre, pe.pers_apellido) AS nombre,
       m.mesa_nombre AS mesa,
       r.rec_nombre AS recinto,
       parroquia.gelo_name AS parroquia,
       canton.gelo_name AS canton
  FROM tec.padron p
  JOIN public.tb_iglesia_persona ip ON ip.igpe_id = p.igpe_id
  JOIN public.tb_iglesia i ON i.igl_id = ip.igl_id
  JOIN public.tb_persona pe ON pe.pers_id = ip.pers_id
  JOIN tec.mesas m ON m.mesa_id = p.mesa_id
  JOIN tec.recintos r ON r.rec_id = m.rec_id
  LEFT JOIN public.tb_geograp parroquia ON parroquia.gelo_id = r.gelo_id
  LEFT JOIN public.tb_geograp canton ON canton.gelo_id = parroquia.gelo_parent_id
 WHERE COALESCE(p.estado, TRUE) = TRUE;

CREATE OR REPLACE VIEW tec.vw_total_escrutinios AS
SELECT e.escr_id,
       cv.nombre,
       e.total_votos AS t_votos,
       cv.cat_orden,
       r.rec_id,
       m.mesa_id,
       COALESCE(m.gelo_id, r.gelo_id) AS gelo_id,
       COALESCE(e.estado, TRUE) AS estado
  FROM tec.escrutinio e
  JOIN tec.categoria_voto cv ON cv.cat_voto_id = e.cat_voto_id
  JOIN tec.mesas m ON m.mesa_id = e.mesa_id
  LEFT JOIN tec.recintos r ON r.rec_id = m.rec_id;
