-- Infraestructura QR. No emite credenciales ni habilita autenticacion al desplegar.
-- No cambiar V1/V2/V3 ni ejecutar repair para instalar esta migracion.
CREATE TABLE tec.acceso_qr_acta (
    qr_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL,
    doc_id INTEGER NOT NULL,
    proce_id INTEGER NOT NULL,
    rec_id INTEGER NOT NULL,
    mesa_id INTEGER NOT NULL,
    miem_id INTEGER NOT NULL,
    usu_id INTEGER NOT NULL,
    tipdoc_id INTEGER NOT NULL,
    doc_version INTEGER NOT NULL,
    estado VARCHAR(16) NOT NULL,
    vigente_desde TIMESTAMP WITH TIME ZONE NOT NULL,
    vigente_hasta TIMESTAMP WITH TIME ZONE NOT NULL,
    emitido_en TIMESTAMP WITH TIME ZONE NOT NULL,
    emitido_por VARCHAR(255) NOT NULL,
    canjeado_en TIMESTAMP WITH TIME ZONE,
    revocado_en TIMESTAMP WITH TIME ZONE,
    motivo_revocacion VARCHAR(255),
    revision BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_acceso_qr_token_hash UNIQUE (token_hash),
    CONSTRAINT uk_acceso_qr_documento UNIQUE (doc_id),
    CONSTRAINT fk_acceso_qr_documento FOREIGN KEY (doc_id) REFERENCES tec.documentos(doc_id),
    CONSTRAINT fk_acceso_qr_proceso FOREIGN KEY (proce_id) REFERENCES tec.proceso_electoral(proce_id),
    CONSTRAINT fk_acceso_qr_recinto FOREIGN KEY (rec_id) REFERENCES tec.recintos(rec_id),
    CONSTRAINT fk_acceso_qr_mesa FOREIGN KEY (mesa_id) REFERENCES tec.mesas(mesa_id),
    CONSTRAINT fk_acceso_qr_presidente FOREIGN KEY (miem_id) REFERENCES tec.miembros_jrv(miem_id),
    CONSTRAINT fk_acceso_qr_usuario FOREIGN KEY (usu_id) REFERENCES public.tb_usuario(usu_id),
    CONSTRAINT fk_acceso_qr_tipo FOREIGN KEY (tipdoc_id) REFERENCES tec.tipo_documentos(tipdoc_id),
    CONSTRAINT ck_acceso_qr_hash CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_acceso_qr_version CHECK (doc_version > 0),
    CONSTRAINT ck_acceso_qr_ventana CHECK (vigente_hasta > vigente_desde),
    CONSTRAINT ck_acceso_qr_estado CHECK (estado IN ('EMITIDO', 'CANJEADO', 'REVOCADO')),
    CONSTRAINT ck_acceso_qr_canje CHECK (estado <> 'CANJEADO' OR canjeado_en IS NOT NULL),
    CONSTRAINT ck_acceso_qr_revocacion CHECK
        (estado <> 'REVOCADO' OR (revocado_en IS NOT NULL AND motivo_revocacion IS NOT NULL))
);
CREATE UNIQUE INDEX uk_acceso_qr_contexto_vigente
    ON tec.acceso_qr_acta (proce_id, mesa_id, tipdoc_id) WHERE estado <> 'REVOCADO';
CREATE INDEX idx_acceso_qr_usuario ON tec.acceso_qr_acta (usu_id);
CREATE INDEX idx_acceso_qr_presidente ON tec.acceso_qr_acta (miem_id);

-- La prueba original se conserva solo del lado servidor dentro de HttpSession.
-- No es JSESSIONID y no se envia como parametro al cliente.
CREATE TABLE tec.sesion_qr_acta (
    sesion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    qr_id BIGINT NOT NULL,
    prueba_hash VARCHAR(64) NOT NULL,
    creada_en TIMESTAMP WITH TIME ZONE NOT NULL,
    expira_en TIMESTAMP WITH TIME ZONE NOT NULL,
    revocada_en TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_sesion_qr_acceso FOREIGN KEY (qr_id) REFERENCES tec.acceso_qr_acta(qr_id),
    CONSTRAINT uk_sesion_qr_acceso UNIQUE (qr_id),
    CONSTRAINT uk_sesion_qr_prueba UNIQUE (prueba_hash),
    CONSTRAINT ck_sesion_qr_hash CHECK (prueba_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_sesion_qr_ventana CHECK (expira_en > creada_en)
);

-- Las auditorias de intentos fallidos se guardan en transaccion independiente.
-- qr_id es una referencia logica: evita bloquearse contra el canje no confirmado.
CREATE TABLE tec.auditoria_acceso_qr (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    qr_id BIGINT,
    proce_id INTEGER,
    mesa_id INTEGER,
    usu_id INTEGER,
    ocurrido_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip VARCHAR(64) NOT NULL,
    user_agent VARCHAR(512) NOT NULL,
    resultado VARCHAR(64) NOT NULL
);
CREATE INDEX idx_auditoria_acceso_qr_fecha ON tec.auditoria_acceso_qr (ocurrido_en);
CREATE INDEX idx_auditoria_acceso_qr_id ON tec.auditoria_acceso_qr (qr_id, ocurrido_en);
