-- Sesiones de la App móvil CONPOCIIECH (API REST /api/v1). Ver docs/api-movil.md.
-- No cambia V1-V6, usuarios, claves ni la configuración de Elytron.
-- Los tokens son opacos (32 bytes aleatorios) y solo se guarda su SHA-256 en hexadecimal:
-- una copia de la BD no permite usar sesiones vigentes.
CREATE TABLE tec.sesion_movil (
    sesion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usu_id INTEGER NOT NULL,
    acceso_hash VARCHAR(64) NOT NULL,
    refresh_hash VARCHAR(64) NOT NULL,
    -- Refresh ya rotado: si vuelve a presentarse, el token fue copiado y se revoca la sesión.
    refresh_anterior_hash VARCHAR(64),
    -- Sesión restringida al cambio de clave obligatorio (usuario no permanente).
    solo_cambio_clave BOOLEAN NOT NULL DEFAULT FALSE,
    creada_en TIMESTAMP WITH TIME ZONE NOT NULL,
    acceso_emitido_en TIMESTAMP WITH TIME ZONE NOT NULL,
    ultimo_uso TIMESTAMP WITH TIME ZONE NOT NULL,
    -- Vida máxima absoluta: tras ella se exige un nuevo inicio de sesión aunque haya actividad.
    expira_absoluta TIMESTAMP WITH TIME ZONE NOT NULL,
    revocada_en TIMESTAMP WITH TIME ZONE,
    motivo_revocacion VARCHAR(40),
    ip VARCHAR(45),
    dispositivo VARCHAR(120),
    CONSTRAINT fk_sesion_movil_usuario FOREIGN KEY (usu_id) REFERENCES public.tb_usuario(usu_id),
    CONSTRAINT uk_sesion_movil_acceso UNIQUE (acceso_hash),
    CONSTRAINT uk_sesion_movil_refresh UNIQUE (refresh_hash),
    CONSTRAINT ck_sesion_movil_acceso_hash CHECK (acceso_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_sesion_movil_refresh_hash CHECK (refresh_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_sesion_movil_refresh_anterior CHECK
        (refresh_anterior_hash IS NULL OR refresh_anterior_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_sesion_movil_vigencia CHECK (expira_absoluta > creada_en),
    CONSTRAINT ck_sesion_movil_revocacion CHECK
        ((revocada_en IS NULL AND motivo_revocacion IS NULL)
         OR (revocada_en IS NOT NULL AND motivo_revocacion IS NOT NULL))
);
CREATE INDEX idx_sesion_movil_usuario_vigente ON tec.sesion_movil (usu_id) WHERE revocada_en IS NULL;
CREATE INDEX idx_sesion_movil_refresh_anterior ON tec.sesion_movil (refresh_anterior_hash)
    WHERE refresh_anterior_hash IS NOT NULL;
