-- Chatbot de ayuda (fase 1): preguntas frecuentes por rol, pantalla y fase del cronograma,
-- consultas sin respuesta (anónimas, 90 días) y canales oficiales de contacto.
-- Menú TRIBUNAL > Ayuda para SITEC-Administrador y SITEC-Tribunal.
-- No modifica tablas existentes.

-- ── Preguntas y respuestas ──────────────────────────────────────────────────
CREATE TABLE tec.ayuda_pregunta (
    ayup_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ayup_pregunta VARCHAR(300) NOT NULL,
    -- Texto plano: la vista lo escapa; nunca se renderiza como HTML.
    ayup_respuesta VARCHAR(4000) NOT NULL,
    ayup_palabras_clave VARCHAR(500),
    -- Pantalla donde se sugiere (p. ej. iglesias.jsf); NULL = cualquier pantalla.
    ayup_pagina VARCHAR(80),
    -- FaseElectoral en la que se prioriza; NULL = cualquier fase.
    ayup_fase VARCHAR(40),
    -- Pantalla a la que lleva «Ir a la pantalla»; solo se muestra si el usuario puede abrirla.
    ayup_enlace_pagina VARCHAR(80),
    ayup_orden INTEGER NOT NULL DEFAULT 100,
    ayup_util_si INTEGER NOT NULL DEFAULT 0,
    ayup_util_no INTEGER NOT NULL DEFAULT 0,
    -- Pregunta + palabras clave + respuesta en minúsculas y sin acentos (lo mantiene la aplicación).
    ayup_texto_busqueda VARCHAR(5000) NOT NULL DEFAULT '',
    ayup_busqueda TSVECTOR GENERATED ALWAYS AS (to_tsvector('spanish'::regconfig, ayup_texto_busqueda)) STORED,
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255)
);
CREATE INDEX idx_ayuda_pregunta_busqueda ON tec.ayuda_pregunta USING GIN (ayup_busqueda);
CREATE INDEX idx_ayuda_pregunta_pagina ON tec.ayuda_pregunta (ayup_pagina);

-- Roles que ven la pregunta; sin filas = todos los roles.
CREATE TABLE tec.ayuda_pregunta_rol (
    ayup_id INTEGER NOT NULL,
    rol_id INTEGER NOT NULL,
    CONSTRAINT pk_ayuda_pregunta_rol PRIMARY KEY (ayup_id, rol_id),
    CONSTRAINT fk_ayuda_pregunta_rol_pregunta FOREIGN KEY (ayup_id) REFERENCES tec.ayuda_pregunta(ayup_id),
    CONSTRAINT fk_ayuda_pregunta_rol_rol FOREIGN KEY (rol_id) REFERENCES public.tb_rol(rol_id)
);

-- ── Consultas sin respuesta: anónimas, enmascaradas y agrupadas ─────────────
CREATE TABLE tec.ayuda_sin_respuesta (
    ayus_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Máx. 200 caracteres; dígitos largos y correos enmascarados antes de guardar.
    ayus_texto VARCHAR(200) NOT NULL,
    ayus_pagina VARCHAR(80) NOT NULL DEFAULT '',
    ayus_veces INTEGER NOT NULL DEFAULT 1,
    ayus_primera_fecha TIMESTAMP NOT NULL,
    ayus_ultima_fecha TIMESTAMP NOT NULL,
    CONSTRAINT uk_ayuda_sin_respuesta UNIQUE (ayus_texto, ayus_pagina)
);
CREATE INDEX idx_ayuda_sin_respuesta_ultima ON tec.ayuda_sin_respuesta (ayus_ultima_fecha);

-- ── Canales oficiales de contacto ───────────────────────────────────────────
CREATE TABLE tec.ayuda_contacto (
    ayuc_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ayuc_tipo VARCHAR(20) NOT NULL,
    ayuc_valor VARCHAR(150) NOT NULL,
    ayuc_etiqueta VARCHAR(100),
    ayuc_horario VARCHAR(100),
    ayuc_orden INTEGER NOT NULL DEFAULT 100,
    estado BOOLEAN DEFAULT TRUE,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255),
    CONSTRAINT ck_ayuda_contacto_tipo CHECK (ayuc_tipo IN ('TELEFONO', 'WHATSAPP', 'CORREO'))
);

-- ── Auditoría Envers (misma convención que V1; sin la columna generada) ──────
CREATE TABLE tec.ayuda_pregunta_aud (
    ayup_id INTEGER NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    ayup_pregunta VARCHAR(300),
    ayup_respuesta VARCHAR(4000),
    ayup_palabras_clave VARCHAR(500),
    ayup_pagina VARCHAR(80),
    ayup_fase VARCHAR(40),
    ayup_enlace_pagina VARCHAR(80),
    ayup_orden INTEGER,
    ayup_texto_busqueda VARCHAR(5000),
    estado BOOLEAN,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255),
    CONSTRAINT pk_ayuda_pregunta_aud PRIMARY KEY (ayup_id, rev),
    CONSTRAINT fk_ayuda_pregunta_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id)
);

CREATE TABLE tec.ayuda_pregunta_rol_aud (
    rev INTEGER NOT NULL,
    ayup_id INTEGER NOT NULL,
    rol_id INTEGER NOT NULL,
    revtype SMALLINT,
    CONSTRAINT pk_ayuda_pregunta_rol_aud PRIMARY KEY (rev, ayup_id, rol_id),
    CONSTRAINT fk_ayuda_pregunta_rol_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id)
);

CREATE TABLE tec.ayuda_contacto_aud (
    ayuc_id INTEGER NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    ayuc_tipo VARCHAR(20),
    ayuc_valor VARCHAR(150),
    ayuc_etiqueta VARCHAR(100),
    ayuc_horario VARCHAR(100),
    ayuc_orden INTEGER,
    estado BOOLEAN,
    f_crea TIMESTAMP,
    f_actualiza TIMESTAMP,
    u_crea VARCHAR(255),
    u_actualiza VARCHAR(255),
    CONSTRAINT pk_ayuda_contacto_aud PRIMARY KEY (ayuc_id, rev),
    CONSTRAINT fk_ayuda_contacto_aud_rev FOREIGN KEY (rev) REFERENCES tec.tec_auditoria(aud_id)
);

-- ── Contactos institucionales: WhatsApp y llamadas ──────────────────────────
INSERT INTO tec.ayuda_contacto (ayuc_tipo, ayuc_valor, ayuc_orden, estado, f_crea, u_crea)
VALUES
    ('WHATSAPP', '+593988994465', 1, TRUE, NOW(), 'flyway'),
    ('WHATSAPP', '+593986076345', 2, TRUE, NOW(), 'flyway'),
    ('WHATSAPP', '+593997103125', 3, TRUE, NOW(), 'flyway'),
    ('TELEFONO', '+593988994465', 4, TRUE, NOW(), 'flyway'),
    ('TELEFONO', '+593986076345', 5, TRUE, NOW(), 'flyway'),
    ('TELEFONO', '+593997103125', 6, TRUE, NOW(), 'flyway');

-- ── Menú TRIBUNAL > Ayuda (Administrador y Tribunal) ────────────────────────
SELECT setval(
    pg_get_serial_sequence('public.tb_menu', 'menu_id'),
    GREATEST((SELECT COALESCE(MAX(menu_id), 1) FROM public.tb_menu), 1),
    TRUE
);
SELECT setval(
    pg_get_serial_sequence('public.tb_menu_rol', 'mero_id'),
    GREATEST((SELECT COALESCE(MAX(mero_id), 1) FROM public.tb_menu_rol), 1),
    TRUE
);

INSERT INTO public.tb_menu (estado, f_crea, u_crea, menu_accion, componente_id, menu_ico, menu_img,
                            menu_nodo_final, menu_nombre, menu_orden, menu_url, menu_padre_id)
SELECT TRUE, NOW(), 'flyway', '/ayuda', 'm_ayuda', 'pi pi-fw pi-question-circle', NULL,
       TRUE, 'Ayuda', 8, '/ayuda.jsf', padre.menu_id
  FROM public.tb_menu padre
 WHERE padre.componente_id = 'm_tribunal'
   AND NOT EXISTS (SELECT 1 FROM public.tb_menu m WHERE m.componente_id = 'm_ayuda');

INSERT INTO public.tb_menu_rol (rol_id, menu_id, estado, f_crea, u_crea)
SELECT r.rol_id, m.menu_id, TRUE, NOW(), 'flyway'
  FROM public.tb_rol r
  JOIN public.tb_menu m ON m.componente_id = 'm_ayuda'
 WHERE r.rol_nombre IN ('SITEC-Administrador', 'SITEC-Tribunal')
   AND NOT EXISTS (SELECT 1 FROM public.tb_menu_rol mr WHERE mr.rol_id = r.rol_id AND mr.menu_id = m.menu_id);
